name: Commit changes

on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download from Google Drive
        run: |
          python dtog.py

      - name: Run the shell script
        run: |
          python run.py

      - name: Commit changes
        id: commit
        run: |
          output_file="output.py"
          values=$(cat "$output_file")
          IFS=',' read -ra value_array <<< "$values"
          files_to_commit=""
          for value in "${value_array[@]}"; do
            echo "$value"
            # Concatenate each value with "git add" command
            git_add_command="git add $value"
            echo "$git_add_command"
            # Concatenate the value to the files_to_commit variable
            files_to_commit+=",$value"
          done
          # Remove leading comma from files_to_commit
          files_to_commit="${files_to_commit:1}"
          echo "FILES_TO_COMMIT=$files_to_commit" >> $GITHUB_ENV

      - name: Final Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: SS08090
          author_email: techicalsolutions68@gmail.com
          message: Auto commit changes
          add: folder1/*
      - name: Final Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: SS08090
          author_email: techicalsolutions68@gmail.com
          message: Auto commit changes
          add: folder2/*

      - name: Final Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: SS08090
          author_email: techicalsolutions68@gmail.com
          message: Auto commit changes
          add: folder3/*
      
      - name: Trigger Workflow 1
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-1
