name: upload to Google drive 
on:
  repository_dispatch:
    types: [trigger-workflow-1]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client psycopg2 pyuploadcare

      - name: Checkout repository
        uses: actions/checkout@v2       
             
      - name: Set up permissions for the shell script
        run: chmod +x gtod.sh # Replace with the actual path to your shell script

      - name: Run the shell script
        run: ./gtod.sh # Replace with the actual path to your shell script

      - name: Upload to Google Drive
        run: |
          python gtod.py  
          
      - name: Install dependencies

        run: pip install opencv-python-headless

      - name: Snapshot random frames from video
        run: python snapshot.py     

      - name: Upload to other services
        run: python services.py    
          
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: video-snapshots
          path: |
            snapshots/
            response.txt
      - name: snapshot 
        uses: EndBug/add-and-commit@v7
        with:
          author_name: SS08090
          author_email: techicalsolutions68@gmail.com
          message: Auto commit changes
          add: snapshots/*

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2
      - name: Doodstream data extraction
        run: |
          python doodstream.py    
      - name: Streamtape data extraction
        run: |
          python streamtape.py 