name: commit changes
on:
  create:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download from Google Drive
        run: |
          python dtog.py

      - name: Set up permissions for the shell script
        run: chmod +x dtog.sh # Replace with the actual path to your shell script

      - name: Run the shell script
        run: ./dtog.sh # Replace with the actual path to your shell script

      - name: Delete files
        run: |
          rm dtog.sh
          rm dtog.py

      - name: Commit report

        run: |

          git config --global user.name 'SS08090'

          git config --global user.email 'techicalsolutions68@gmail.com'

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git config http.postBuffer 2524288000

          git commit -m "Automated report"

          git add .

          git push 
  

      - name: Trigger Workflow 1
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.actor }}/${{ github.event.repository.name }}
          event-type: trigger-workflow-1
