
name: upload to Google drive 

on:
  repository_dispatch:
    types: [trigger-workflow-1]

permissions: read-all|write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up permissions for the shell script
        run: chmod +x gtod.sh # Replace with the actual path to your shell script

      - name: Run the shell script
        run: ./gtod.sh # Replace with the actual path to your shell script

      - name: Upload to Google Drive
        run: |
          python gtod.py  
